In [11]:
import numpy

def matrix_factorization(R, P, Q, K, steps=10000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - numpy.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = numpy.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - numpy.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        if e < 0.001:
            break
#     print(numpy.shape(P))
#     print(numpy.shape(Q))

    return P, Q

R = [[5.42, 7.54, 7.04, 6.84, 6.0, 6.7 ],
       [6.74, 7.96, 7.5 , 6.72, 6.0, 6.6 ],
       [5.99, 5.29, 6.2 , 7.06, 6.0, 6.89],
       [6.2 , 6.21, 5.86, 6.32, 6.0, 6.26],
       [7.34, 6.98, 7.72, 6.99, 9.0, 7.33],
       [7.72, 7.68, 7.24, 6.41, 7.0, 6.51]]

R = numpy.array(R)
N = len(R)
M = len(R[0])
K = 3

P = numpy.random.rand(N,K)
Q = numpy.random.rand(M,K)

U, V = matrix_factorization(R, P, Q, K)
nR = numpy.dot(U, V)

print(nR)


[[6.04608089 7.32332908 6.91436134 6.89398005 5.64633927 6.68558972]
 [6.63502843 8.03814303 7.33252526 6.72720678 6.10321038 6.62193478]
 [5.65054185 5.45778967 6.16895148 6.99770352 6.2149248  6.8706853 ]
 [5.89508065 6.12855014 6.25003482 6.21658691 6.08977653 6.1969928 ]
 [7.80032385 6.89620158 7.51172945 7.06670813 8.6977158  7.34244365]
 [7.26061574 7.75765188 7.37158349 6.3588199  7.2251429  6.50339856]]


In [20]:
print(numpy.shape(R))
print(U)
print(numpy.shape(U))

(6, 6)
[[1.82513823 1.88340254 0.30038588]
 [2.27904793 1.50963298 0.46548049]
 [0.89720809 2.24111357 0.91197102]
 [1.40733951 1.65623828 0.9178431 ]
 [1.52460136 1.62173192 2.15345136]
 [2.2246444  1.18840753 1.2372304 ]]
(6, 3)


In [22]:
print(nQ.T)
print(numpy.shape(nQ))

[[1.83457833 2.52922202 1.98537999 1.34832694 1.32573191 1.26123422]
 [1.23368837 1.33915166 1.59333302 2.24434862 1.4019736  2.20992029]
 [1.36951345 0.40120576 0.88268144 0.64677975 2.06274173 0.85057135]]
(6, 3)


In [38]:
aList = [123, 'xyz', 'zara', 'abc']

strr = str(aList)

In [39]:
strr

"[123, 'xyz', 'zara', 'abc']"

In [44]:
if "123" in strr:
    print("good")

good
